[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ppd-telemetry-calendar"
version = "0.0.1"
description = "RSuite telemetry calendar for Streamlit"
requires-python = ">=3.11"
dependencies = ["streamlit>=1.30"]

[tool.setuptools.packages.find]
include = ["ppd_telemetry_calendar*"]

[tool.setuptools.package-data]
ppd_telemetry_calendar = ["frontend/build/**/*", "pyproject.toml"]

[[tool.streamlit.component.components]]
name = "telemetry_calendar"
asset_dir = "frontend/build"
